#!/bin/bash
#
#  Command Line Interface to start all services associated with the Tutorial
#

set -e

echo -e "Please checkout the \033[1;36mNGSI-LD\033[0m branch of this repository to run this tutorial."
